name: Check

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

permissions: {}

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nixos-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' \
            | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1
        with:
          extra_nix_config: |
            system-features = nixos-test benchmark big-parallel kvm

      - name: Flake check
        run: nix flake check --print-build-logs

      - name: Evaluate aarch64-linux
        run: |
          nix eval .#packages.aarch64-linux.claude-desktop.drvPath
          nix eval .#checks.aarch64-linux.vm.drvPath

      - name: Collect screenshot
        run: nix build .#checks.x86_64-linux.vm

      - uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
        with:
          name: screenshot
          path: result/*.png
